name: spy_app
description: Spy - Haini Bul

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shared_preferences: ^2.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  wakelock_plus: ^1.2.8
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # ← just the version here


# ↓ Launcher icons config goes at the TOP LEVEL, not inside dev_dependencies
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/my_real_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/categories.json
    - assets/characters/pic_1.png
    - assets/characters/pic_2.png
    - assets/characters/pic_3.png
    - assets/characters/pic_4.png
    - assets/characters/pic_5.png
    - assets/characters/pic_6.png
    - assets/characters/pic_7.png
    - assets/characters/pic_8.png
    - assets/characters/pic_9.png
    - assets/my_imposter.png
    - assets/my_real_icon.png
    - assets/my_crew.png
